### PR TITLE
Port to dune

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by smorimoto** [comment]
Besides porting everything to dune, I made it easier to bootstrap the development environment by adding each dummy package context. This is a very important PR to adopt the odoc-based documentation system in the subsequent PR, #71.

**Comment by smorimoto** [comment]
Anyway, it will probably not actually be mergeable until #71 becomes mergeable. Otherwise, many documents will be messy and useless due to a lot of source relocations.

**Comment by smorimoto** [comment]
@ksuenaga Ready to merge!

**Comment by smorimoto** [comment]
Now you can use [`ppx_expect`](https://github.com/janestreet/ppx_expect) in your tutorials. This might be good because it's easier for users to understand, and it's easier to manipulate the code and get results.

```ml
(* OCaml の equality は (=) でチェック *)
let%expect_test _ =
  Printf.printf "%b" (5 = 2 || 9 > -5);
  [%expect {| true |}]

(* 型推論 *)
let%expect_test _ =
  (* x という名前を 1 + 2 * 3 の評価結果につける．*)
  (* x を 1 + 2 * 3 の評価結果に束縛する *)
  let x = 1 + (2 * 3) in
  let result = x - 10 in
  Printf.printf "%d" result;
  [%expect {| -3 |}];
  let x : int = 1 + (2 * 3) in
  Printf.printf "%d" x;
  [%expect {| 7 |}];
  let x = 4 < 5 in
  Printf.printf "%b" x;
  [%expect {| true |}]
```

The following pages should help you understand the advantages of this:

- https://ianthehenry.com/posts/my-kind-of-repl
- https://dune.readthedocs.io/en/stable/tests.html

**Comment by ksuenaga** [comment]
@smorimoto Thanks!  Let me review the changes and merge the PR!

**Comment by smorimoto** [comment]
@ksuenaga Once this is merged, I will open a PR to improve docs 🙃

**Review by ksuenaga — APPROVED** [review]
Looks good, thanks!!!!

**Pull request merged**
