### PR TITLE
Add tuareg to arguments of depext

### PR DESCRIPTION
**Pull request by ushitora-anqou**
It will install Emacs if it does not exist.

### CODE REVIEW

**Comment by smorimoto** [comment]
By the way, a neat trick is to pass the install flag to depext so that you just run depext once.

**Comment by smorimoto** [comment]
But note that from opam 2.1, depext is built-in, so depext is no longer needed. With the new integrated system, there is no more the need to call opam depext; it's completely transparent. So calling depext with opam 2.1 will behave as opam 2.0; install plugin depext and calls it. (The main inconvenience is that you will do an external dependency check twice. Well, it's fine.)

**Review by ksuenaga — APPROVED** [review]

**Comment by ksuenaga** [comment]
@smorimoto Thanks!  Maybe (next year?) we can delete the calls to `opam depext`.

**Comment by smorimoto** [comment]
No, it should be summer. 2.1 is almost there!

**Pull request merged**
